### ISSUE TITLE
Overwriting collectd.conf breaks graphs in some environments

### ISSUE THREAD

**Issue by lukyjay** [sprater/freenas-disktemp-graphs#1]
Hi

I've cloned and executed the install script through SSH as instructed and all seems well, but there's no graph in the FreeNAS gui for harddrive temperatures.

`root@freenas:/mnt/JRaid/Applications/FreeNAS/freenas-disktemp-graphs # ./install_disktemp_graphs.sh
Stopping collectd.
Waiting for PIDS: 5642.
Starting collectd.
plugin_load: plugin "aggregation" successfully loaded.
plugin_load: plugin "cpu" successfully loaded.
plugin_load: plugin "cputemp" successfully loaded.
plugin_load: plugin "ctl" successfully loaded.
plugin_load: plugin "df" successfully loaded.
plugin_load: plugin "disk" successfully loaded.
plugin_load: plugin "exec" successfully loaded.
plugin_load: plugin "geom_stat" successfully loaded.
plugin_load: plugin "interface" successfully loaded.
plugin_load: plugin "load" successfully loaded.
plugin_load: plugin "memory" successfully loaded.
plugin_load: plugin "network" successfully loaded.
plugin_load: plugin "processes" successfully loaded.
plugin_load: plugin "rrdtool" successfully loaded.
plugin_load: plugin "swap" successfully loaded.
plugin_load: plugin "uptime" successfully loaded.
Performing sanity check on nginx configuration:
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful
Stopping nginx.
Waiting for PIDS: 3142.
Performing sanity check on nginx configuration:
nginx: the configuration file /usr/local/etc/nginx/nginx.conf syntax is ok
nginx: configuration file /usr/local/etc/nginx/nginx.conf test is successful
Starting nginx.
Stopping django.
Waiting for PIDS: 5509.
root@freenas:/mnt/JRaid/Applications/FreeNAS/freenas-disktemp-graphs #
`

How can I troubleshoot this?

**Comment by lukyjay** [comment]
In fact this has stopped all reports in the GUI from working.

**Comment by lukyjay** [comment]
The issue is with how collectd.conf is not updated, but instead replaced. I had to look at my backup and revert the following changes:

1. Line 1, freenas.lan > freenas.local
2. Line 35, cpu > percent
3. Line 47, re-add the line that was deleted:     ValuesPercentage True

Then execute:
service collectd restart
service nginx restart
service django restart

and it works. To fix this problem you might need to rethink how you're adding those lines in to the collectd.conf. My apologies as I don't have the technical knowledge to provide a better solution.

Thank you

**Comment by sprater** [comment]
Thank you, @lukyjay .  I will improve my scripts to not overwrite collectd, but just add the line that is needed.
Out of curiosity, what version of FreeNAS are you running?

**Comment by lukyjay** [comment]
Hi I'm using 11.1-U1. Not sure why we have different configurations. I did
a fresh install around April 2017. Maybe you have an old configuration file
from the 9.x days?

**Comment by sprater** [comment]
That could be, which exposes a dangerous assumption I made about the configuration files.  I’ll modify the code to tread more lightly.  Thanks again for posting this issue, I’ll get a fix out shortly.

**Comment by sprater** [comment]
@lukyjay :  I pushed a fix, go ahead and pull the repo and let me know if it works correctly now.
